### ISSUE TITLE
new Sappinfo File throws error

### ISSUE THREAD

**Issue by zdavatz** [zdavatz/cpp2sqlite#101]
just one field changed.
```
terminate called after throwing an instance of 'xlnt::exception'
what():  xlnt::exception : failed to find zip header
./build.sh: Zeile 51:  7446 Abgebrochen./cpp2sqlite --verbose --inDir $SRC_DIR/input
```

https://ywesee.slack.com/files/U27FC8WLA/FNX2R2UF4/kopie_von_33_ss_peripartal_sz_endliste_tw_alles_deutsch_10.10.2019.xlsx

**Comment by bettar** [comment]
Steps to reproduce please.

The file sappinfo.xlsx is in the `input` directory, part of the git repository and a `git pull` doesn't show any new file.

I tried overwriting the file sappinfo.xlsx with the one you linked above, then running the utility `cpp2sqlite` but I couldn't reproduce the error. This indicates to me that the problem might be in your build.sh file rather than the sappinfo.xlsx file. Your error message refers to a "zip header"... I wonder what that refers to.

**Comment by zdavatz** [comment]
running the build script with these steps:
```
STEP_DOWNLOAD=true
STEP_BUILD_APPS=true
STEP_RUN_C2S=true
STEP_RUN_PHARMA=true
```

**Comment by zdavatz** [comment]
this seems to be a slack download issue.
